version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./requirements/nginx
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - 443:443
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   restart: always
  #   networks:
  #     - network

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    ports:
      - 3306:3306
    # restart: always
    env_file:
      - .env

  # wordpress:
  #   container_name: wordpress
  #   build:
  #     context: ./requirements/wordpress
  
  #   depends_on:
  #     - mariadb
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - network

volumes:
  mariadb_data:
  wordpress_data:

networks:
  network: